INSERT INTO `pages` VALUES(390,0,10,1,1,'PL','Integer lobortis egestas varius. Nunc a lacus sed nibh sagittis consectetur elementum a justo. Nulla diam purus, viverra eget aliquet eget, laoreet vitae sem. Fusce vel dui non libero dapibus pellentesque. Donec fringilla porta felis. Aliquam tortor nisi, aliquet quis accumsan in, elementum at mauris. fgdsfgdsfdsdf<br />
<br />
Nam pellentesque, nibh sed molestie vulputate, ligula tellus scelerisque dolor, sit amet adipiscing neque neque sit amet diam. Donec sodales ligula vitae mi hendrerit ac euismod urna pretium. Aliquam ultrices risus turpis, eget iaculis mauris. Proin mi nulla, tincidunt ut fringilla ut, ornare nec velit. Praesent viverra odio quis massa fringilla lacinia. Aliquam eleifend justo felis, a lobortis justo. Ut sit amet est erat. Cras faucibus erat at augue eleifend aliquam.','2012-08-07 20:58:55','2013-05-15 16:28:15','127.0.0.1','127.0.0.1','pl-1','main_page.tpl','Windu','WinduCMS','cms, windu, system','',4493,NULL,0,'simple_page.tpl',5,0,'djgpdqbqrzfh',1,NULL,390,'',0,'',0,NULL);
INSERT INTO `pages` VALUES(474,390,11,2,3,'Elementy strony','Sprzedam meble kuchenne w okleinie drewnianej. Mają zaledwie 2 lata, sprzedaję dom, a nowy właściciel chce mieć kuchnię nowoczesną. <br />
W skład kuchni wchodzi 6 szafek górnych (w tym narozna), 6 szafek dolnych (w tym naorożna), szafka pod zlew i pod kuchenkę oraz blat z IKEA. Cena całości 1500 zł. Można kupic tylko część. Dowóz na własna rękę. Okolice Warszawy. Więcej szczegółów: 661 881 599','2012-09-11 18:51:11','2013-05-11 18:53:34','127.0.0.1','127.0.0.1','elementy-strony','simple_page.tpl','','','','',8,NULL,0,'simple_page.tpl',5,0,'phtytfpjmnqj',NULL,NULL,390,NULL,0,NULL,0,NULL);
INSERT INTO `pages` VALUES(475,474,1,1,9,'Tagi','{{W name=tagsShowNormal}}','2012-09-11 18:51:24','2012-10-14 17:48:27','127.0.0.1','127.0.0.1','tagi','tags.tpl','','','','',45,NULL,0,NULL,5,0,'ryvwwwacmywd',NULL,NULL,390,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(476,474,1,1,10,'Wyszukiwarka','{{W name=searchShowNormal showAuthor=0 showContent=1 showDate=0 length=240}}','2012-09-11 18:51:32','2013-02-04 08:57:19','127.0.0.1','127.0.0.1','wyszukiwarka','simple_page.tpl','','','','',14,NULL,0,NULL,5,0,'pjkacktgsgwc',NULL,NULL,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(637,474,1,1,16,'Rejestracja','{{W name=userRegister successPage=638}}','2012-09-27 19:39:10','2012-10-15 15:02:58','127.0.0.1','127.0.0.1','rejestracja','simple_page_nopad.tpl','','','','',35,NULL,0,NULL,5,0,'jsjftakmbxbh',0,0,390,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(638,474,1,1,11,'Dziękujemy za rejestracje','<strong>Dziękujemy za dokonanie rejestracji!</strong><br />
<br />
Na podany podczas rejestracji adres email została wysłana wiadomość z linkiem aktywującym twoje konto w naszym serwisie.<br />
Odbierz pocztę i kliknij w link w celu aktywacji twojego konta.','2012-09-27 19:39:15','2012-11-26 16:04:16','127.0.0.1','94.75.66.24','dziekujemy-za-rejestracje','simple_page.tpl','','','','',4,NULL,0,NULL,5,0,'gndxhrdcrqas',0,0,390,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(639,474,1,1,15,'Panel użytkownika','{{W name=userPanel nocache}}','2012-09-27 19:39:24','2012-10-15 14:58:29','127.0.0.1','127.0.0.1','panel-uzytkownika','simple_page_nopad.tpl','','','','',14,NULL,0,NULL,5,0,'wsmcwcmrzhrb',0,0,390,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(659,0,10,1,2,'EN','Integer lobortis egestas varius. Nunc a lacus sed nibh sagittis consectetur elementum a justo. Nulla diam purus, viverra eget aliquet eget, laoreet vitae sem. Fusce vel dui non libero dapibus pellentesque. Donec fringilla porta felis. Aliquam tortor nisi, aliquet quis accumsan in, elementum at mauris.<br />
<br />
Nam pellentesque, nibh sed molestie vulputate, ligula tellus scelerisque dolor, sit amet adipiscing neque neque sit amet diam. Donec sodales ligula vitae mi hendrerit ac euismod urna pretium. Aliquam ultrices risus turpis, eget iaculis mauris. Proin mi nulla, tincidunt ut fringilla ut, ornare nec velit. Praesent viverra odio quis massa fringilla lacinia. Aliquam eleifend justo felis, a lobortis justo. Ut sit amet est erat. Cras faucibus erat at augue eleifend aliquam.','2012-09-29 18:27:33','2013-05-11 18:53:34','127.0.0.1','127.0.0.1','en-7','main_page.tpl','Windu','WinduCMS','WinduCMS','',10,NULL,0,'simple_page.tpl',5,0,'hhfnpttyayfg',1,0,'','',0,'',0,NULL);
INSERT INTO `pages` VALUES(660,659,1,1,18,'Page','Vivamus ornare interdum pharetra. Etiam at leo eget neque ullamcorper accumsan congue ut risus. Integer rhoncus iaculis mi consequat rutrum. Fusce bibendum tempor feugiat. Vivamus vitae eros dolor. Praesent vestibulum urna sit amet diam varius commodo at et elit. Sed gravida, quam eget dictum ultricies, odio justo sollicitudin tortor, vitae dignissim lectus nunc non sapien. Duis pellentesque aliquet nibh vel posuere.<br />
<br />
Praesent posuere scelerisque nisi, et bibendum libero facilisis ac. Etiam a enim id urna pharetra hendrerit. Vivamus vel nunc ac ligula scelerisque bibendum eget et nibh. Suspendisse fringilla cursus massa, id vestibulum nunc tempor sit amet. Aliquam auctor sem tempus nunc dignissim imperdiet. Nam sapien purus, aliquam ut pellentesque eu, feugiat id sapien. Aenean faucibus luctus pharetra. Quisque eu eros neque.<br />
<br />
Donec vestibulum aliquam urna, eu auctor lectus blandit sit amet. Praesent eget est in augue porta iaculis. Aliquam rutrum, justo vitae gravida dictum, ante ligula scelerisque magna, sed sollicitudin urna mauris eget est. Nam ac porttitor dolor. Sed laoreet molestie orci sed lacinia. Morbi tellus nibh, dapibus eget mattis et, varius nec orci. Vestibulum est elit, aliquam et aliquam ut, eleifend quis nunc. Proin vitae ligula nec lorem volutpat cursus. Praesent placerat nunc vitae nunc pharetra posuere. Nam eleifend porttitor purus.<br />
<br />
In sed augue ligula. Ut malesuada lacinia condimentum. Donec in nisi mauris, quis pretium diam. Etiam nec arcu id elit imperdiet gravida. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras bibendum consectetur tellus, a ultrices diam cursus in. Sed venenatis lacus vel metus vulputate euismod condimentum nulla consectetur. Duis bibendum commodo enim nec tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat facilisis vestibulum. Phasellus tincidunt euismod luctus. In quis diam arcu. Mauris metus odio, venenatis et sollicitudin hendrerit, molestie ac arcu. Fusce semper pulvinar nisl nec ullamcorper.','2012-09-29 18:27:40','2013-02-02 22:08:32','127.0.0.1','127.0.0.1','page','simple_page.tpl','','','','',3,NULL,0,NULL,5,0,'fdnmjrpcydwx',0,0,659,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(735,390,1,1,2,'Podstrona','Vivamus ornare interdum pharetra. Etiam at leo eget neque ullamcorper accumsan congue ut risus. Integer rhoncus iaculis mi consequat rutrum. Fusce bibendum tempor feugiat. Vivamus vitae eros dolor. Praesent vestibulum urna sit amet diam varius commodo at et elit. Sed gravida, quam eget dictum ultricies, odio justo sollicitudin tortor, vitae dignissim lectus nunc non sapien. Duis pellentesque aliquet nibh vel posuere.<br />
<br />
Praesent posuere scelerisque nisi, et bibendum libero facilisis ac. Etiam a enim id urna pharetra hendrerit. Vivamus vel nunc ac ligula scelerisque bibendum eget et nibh. Suspendisse fringilla cursus massa, id vestibulum nunc tempor sit amet. Aliquam auctor sem tempus nunc dignissim imperdiet ien purus, aliquam ut pellentesque eu, feugiat id sapien. Aenean faucibus luctus pharetra. Quisque eu eros neque.<br />
<br />
Donec vestibulum aliquam urna, eu auctor lectus blandit sit amet. Praesent eget est in augue porta iaculis. Aliquam rutrum, justo vitae gravida dictum, ante ligula scelerisque magna, sed sollicitudin urna mauris eget est. Nam ac porttitor dolor. Sed laoreet molestie orci sed lacinia. Morbi tellus nibh, dapibus eget mattis et, varius nec orci. Vestibulum est elit, aliquam et aliquam ut, eleifend quis nunc. Proin vitae ligula nec lorem volutpat cursus. Praesent placerat nunc vitae nunc pharetra posuere. Nam eleifend porttitor purus.<br />
<br />
In sed augue ligula. Ut malesuada lacinia condimentum. Donec in nisi mauris, quis pretium diam. Etiam nec arcu id elit imperdiet gravida. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras bibendum consectetur tellus, a ultrices diam cursus in. Sed venenatis lacus vel metus vulputate euismod condimentum nulla consectetur. Duis bibendum commodo enim nec tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat facilisis vestibulum. Phasellus tincidunt euismod luctus. In quis diam arcu. Mauris metus odio, venenatis et sollicitudin hendrerit, molestie ac arcu. Fusce semper pulvinar nisl nec ullamcorper.','2012-10-15 13:24:21','2013-05-17 15:43:10','127.0.0.1','127.0.0.1','podstrona','simple_page.tpl','','','','',8,NULL,0,NULL,5,0,'brpyzaaztsbp',0,0,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(737,390,12,1,5,'Galeria','{{W name=galleryFancybox images=$imagesDB->getByBucket(737)}}','2012-10-15 13:24:31','2013-05-11 18:53:34','127.0.0.1','127.0.0.1','galeria','simple_page.tpl','','','','',6,NULL,0,'simple_page.tpl',5,0,'abfmpwyrbdhm',0,0,390,'',0,'',0,NULL);
INSERT INTO `pages` VALUES(738,390,3,1,7,'Link do CMS','http://www.windu.org','2012-10-15 13:24:38','2013-05-11 18:53:34','127.0.0.1','127.0.0.1','link-do-cms','simple_page.tpl','','','','',6,NULL,0,NULL,5,0,'bnvmpvvmdmst',0,0,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(739,390,11,1,6,'Grupa','{{W name=contentListShow type=lastest elementtype=1 bucket=$page->id showSource=0 showAuthor=0 length=200}}','2012-10-15 13:24:49','2013-05-11 18:53:34','127.0.0.1','127.0.0.1','grupa','simple_page.tpl','','','','',7,NULL,0,'simple_page.tpl',5,0,'qscjvfpvcxpj',0,0,390,'',0,'',0,NULL);
INSERT INTO `pages` VALUES(740,739,1,1,12,'Lorem ipsum','Praesent posuere scelerisque nisi, et bibendum libero facilisis ac. Etiam a enim id urna pharetra hendrerit. Vivamus vel nunc ac ligula scelerisque bibendum eget et nibh. Suspendisse fringilla cursus massa, id vestibulum nunc tempor sit amet. Aliquam auctor sem tempus nunc dignissim imperdiet. Nam sapien purus, aliquam ut pellentesque eu, feugiat id sapien. Aenean faucibus luctus pharetra. Quisque eu eros neque.<br />
<br />
Donec vestibulum aliquam urna, eu auctor lectus blandit sit amet. Praesent eget est in augue porta iaculis. Aliquam rutrum, justo vitae gravida dictum, ante ligula scelerisque magna, sed sollicitudin urna mauris eget est. Nam ac porttitor dolor. Sed laoreet molestie orci sed lacinia. Morbi tellus nibh, dapibus eget mattis et, varius nec orci. Vestibulum est elit, aliquam et aliquam ut, eleifend quis nunc. Proin vitae ligula nec lorem volutpat cursus. Praesent placerat nunc vitae nunc pharetra posuere. Nam eleifend porttitor purus.<br />
<br />
In sed augue ligula. Ut malesuada lacinia condimentum. Donec in nisi mauris, quis pretium diam. Etiam nec arcu id elit imperdiet gravida. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras bibendum consectetur tellus, a ultrices diam cursus in. Sed venenatis lacus vel metus vulputate euismod condimentum nulla consectetur. Duis bibendum commodo enim nec tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat facilisis vestibulum. Phasellus tincidunt euismod luctus. In quis diam arcu. Mauris metus odio, venenatis et sollicitudin hendrerit, molestie ac arcu. Fusce semper pulvinar nisl nec ullamcorper.','2012-10-15 13:25:04','2013-02-02 13:16:49','127.0.0.1','127.0.0.1','lorem-ipsum','simple_page.tpl','','','','',6,NULL,0,NULL,5,0,'xgcgyqfsbrwr',0,0,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(741,739,1,1,13,'Maecenas volutpat','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum suscipit vulputate rutrum. Maecenas dictum ultrices diam, a semper eros hendrerit a. Vivamus mattis varius odio tempus egestas. Quisque ornare vestibulum urna quis bibendum. Ut pharetra mi at justo semper non commodo orci blandit. Mauris sodales congue risus non lacinia. Cras tortor lectus, hendrerit vel faucibus sed, eleifend eget arcu. Praesent rutrum arcu aliquet mauris cursus gravida. Nulla varius commodo libero id interdum. Nullam tempus metus sagittis lacus adipiscing lobortis. Aenean quis nisl ipsum. Ut iaculis dolor vitae risus tincidunt bibendum. Suspendisse commodo cursus justo, ac tempus sem laoreet a. Proin in augue dolor, non lobortis lacus. Vestibulum molestie facilisis velit, a tempus neque sagittis eget.<br />
<br />
Vivamus ornare interdum pharetra. Etiam at leo eget neque ullamcorper accumsan congue ut risus. Integer rhoncus iaculis mi consequat rutrum. Fusce bibendum tempor feugiat. Vivamus vitae eros dolor. Praesent vestibulum urna sit amet diam varius commodo at et elit. Sed gravida, quam eget dictum ultricies, odio justo sollicitudin tortor, vitae dignissim lectus nunc non sapien. Duis pellentesque aliquet nibh vel posuere.<br />
<br />
Praesent posuere scelerisque nisi, et bibendum libero facilisis ac. Etiam a enim id urna pharetra hendrerit. Vivamus vel nunc ac ligula scelerisque bibendum eget et nibh. Suspendisse fringilla cursus massa, id vestibulum nunc tempor sit amet. Aliquam auctor sem tempus nunc dignissim imperdiet. Nam sapien purus, aliquam ut pellentesque eu, feugiat id sapien. Aenean faucibus luctus pharetra. Quisque eu eros neque.<br />
<br />
Donec vestibulum aliquam urna, eu auctor lectus blandit sit amet. Praesent eget est in augue porta iaculis. Aliquam rutrum, justo vitae gravida dictum, ante ligula scelerisque magna, sed sollicitudin urna mauris eget est. Nam ac porttitor dolor. Sed laoreet molestie orci sed lacinia. Morbi tellus nibh, dapibus eget mattis et, varius nec orci. Vestibulum est elit, aliquam et aliquam ut, eleifend quis nunc. Proin vitae ligula nec lorem volutpat cursus. Praesent placerat nunc vitae nunc pharetra posuere. Nam eleifend porttitor purus.','2012-10-15 13:25:07','2013-02-02 13:16:57','127.0.0.1','127.0.0.1','maecenas-volutpat','simple_page.tpl','','','','',6,NULL,0,NULL,5,0,'mnzmkgrabvgr',0,0,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(742,739,1,1,11,'Curabitur velit nulla','In sed augue ligula. Ut malesuada lacinia condimentum. Donec in nisi mauris, quis pretium diam. Etiam nec arcu id elit imperdiet gravida. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras bibendum consectetur tellus, a ultrices diam cursus in. Sed venenatis lacus vel metus vulputate euismod condimentum nulla consectetur. Duis bibendum commodo enim nec tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat facilisis vestibulum. Phasellus tincidunt euismod luctus. In quis diam arcu. Mauris metus odio, venenatis et sollicitudin hendrerit, molestie ac arcu. Fusce semper pulvinar nisl nec ullamcorper.','2012-10-15 13:25:10','2013-02-02 13:16:38','127.0.0.1','127.0.0.1','curabitur-velit-nulla','simple_page.tpl','','','','',4,NULL,0,NULL,5,0,'naydchzpmtaq',0,0,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(743,739,1,1,15,'Sed quis libero','Vivamus ornare interdum pharetra. Etiam at leo eget neque ullamcorper accumsan congue ut risus. Integer rhoncus iaculis mi consequat rutrum. Fusce bibendum tempor feugiat. Vivamus vitae eros dolor. Praesent vestibulum urna sit amet diam varius commodo at et elit. Sed gravida, quam eget dictum ultricies, odio justo sollicitudin tortor, vitae dignissim lectus nunc non sapien. Duis pellentesque aliquet nibh vel posuere.<br />
<br />
Praesent posuere scelerisque nisi, et bibendum libero facilisis ac. Etiam a enim id urna pharetra hendrerit. Vivamus vel nunc ac ligula scelerisque bibendum eget et nibh. Suspendisse fringilla cursus massa, id vestibulum nunc tempor sit amet. Aliquam auctor sem tempus nunc dignissim imperdiet. Nam sapien purus, aliquam ut pellentesque eu, feugiat id sapien. Aenean faucibus luctus pharetra. Quisque eu eros neque.<br />
<br />
Donec vestibulum aliquam urna, eu auctor lectus blandit sit amet. Praesent eget est in augue porta iaculis. Aliquam rutrum, justo vitae gravida dictum, ante ligula scelerisque magna, sed sollicitudin urna mauris eget est. Nam ac porttitor dolor. Sed laoreet molestie orci sed lacinia. Morbi tellus nibh, dapibus eget mattis et, varius nec orci. Vestibulum est elit, aliquam et aliquam ut, eleifend quis nunc. Proin vitae ligula nec lorem volutpat cursus. Praesent placerat nunc vitae nunc pharetra posuere. Nam eleifend porttitor purus.','2012-10-15 13:25:13','2013-02-02 13:17:18','127.0.0.1','127.0.0.1','sed-quis-libero','simple_page.tpl','','','','',4,NULL,0,NULL,5,0,'nhxhasvwmfkh',0,0,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(744,739,1,1,14,'Nullam erat','Vivamus ornare interdum pharetra. Etiam at leo eget neque ullamcorper accumsan congue ut risus. Integer rhoncus iaculis mi consequat rutrum. Fusce bibendum tempor feugiat. Vivamus vitae eros dolor. Praesent vestibulum urna sit amet diam varius commodo at et elit. Sed gravida, quam eget dictum ultricies, odio justo sollicitudin tortor, vitae dignissim lectus nunc non sapien. Duis pellentesque aliquet nibh vel posuere.<br />
<br />
Praesent posuere scelerisque nisi, et bibendum libero facilisis ac. Etiam a enim id urna pharetra hendrerit. Vivamus vel nunc ac ligula scelerisque bibendum eget et nibh. Suspendisse fringilla cursus massa, id vestibulum nunc tempor sit amet. Aliquam auctor sem tempus nunc dignissim imperdiet. Nam sapien purus, aliquam ut pellentesque eu, feugiat id sapien. Aenean faucibus luctus pharetra. Quisque eu eros neque.<br />
<br />
Donec vestibulum aliquam urna, eu auctor lectus blandit sit amet. Praesent eget est in augue porta iaculis. Aliquam rutrum, justo vitae gravida dictum, ante ligula scelerisque magna, sed sollicitudin urna mauris eget est. Nam ac porttitor dolor. Sed laoreet molestie orci sed lacinia. Morbi tellus nibh, dapibus eget mattis et, varius nec orci. Vestibulum est elit, aliquam et aliquam ut, eleifend quis nunc. Proin vitae ligula nec lorem volutpat cursus. Praesent placerat nunc vitae nunc pharetra posuere. Nam eleifend porttitor purus.','2012-10-15 13:25:16','2013-02-02 13:17:08','127.0.0.1','127.0.0.1','nullam-erat','simple_page.tpl','','','','',4,NULL,0,NULL,5,0,'jbprckahcjzc',0,0,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(745,390,13,1,4,'Aktualności','{{W name=newsNormal newsGroup=745 showAuthor=0 showDate=0 length=300}}','2012-10-15 15:10:25','2013-05-18 12:23:46','127.0.0.1','127.0.0.1','aktualnosci-5','simple_page.tpl','','','','',6,NULL,0,'news_page.tpl',5,0,'jmjpwqwzngxa',0,0,390,'',0,'',0,NULL);
INSERT INTO `pages` VALUES(746,745,2,1,8,'Quisque enim tortor, vehicula at hendrerit','Praesent ultrices auctor ligula, id pulvinar orci varius a. Aliquam tincidunt enim eu nulla dapibus mollis. Vestibulum pharetra ligula ac dolor ultrices vel aliquet tortor imperdiet. Nam ultrices accumsan eros sed volutpat. Nunc ac ornare magna. In pharetra orci sit amet justo fringilla venenatis. Quisque enim tortor, vehicula at hendrerit sed, iaculis in lacus. Aliquam egestas, libero sit amet vehicula pretium, urna libero condimentum nulla, at fringilla lectus velit sed risus.<br />
<br />
Mauris sem sem, fringilla id consequat id, elementum rhoncus orci. Phasellus purus magna, tincidunt at tincidunt in, adipiscing ut nisl. Nunc fermentum, neque nec volutpat molestie, nunc enim semper urna, et pellentesque est urna sit amet leo. Nulla facilisi. Etiam aliquet erat nunc, nec accumsan odio. In hac habitasse platea dictumst. Cras aliquet sagittis metus, vitae pulvinar est sagittis vitae. Ut ultricies dapibus ipsum vitae vulputate. Vivamus feugiat rhoncus posuere. Curabitur in est sed dolor adipiscing scelerisque. Quisque dignissim dui eu ligula ornare sollicitudin. Aliquam at ligula diam, eget posuere enim. Phasellus nibh eros, interdum nec ultrices id, pharetra vehicula metus. Phasellus vitae magna in felis commodo semper. Suspendisse potenti. Donec ac lorem vel elit facilisis pretium a id purus.','2012-10-15 15:11:13','2013-02-03 15:50:00','127.0.0.1','127.0.0.1','quisque-enim-tortor-vehicula-at-hendrerit-9','news_page.tpl','','','','',1,'2012-10-15',0,NULL,5,0,'wkhdwhgfhfjh',0,0,390,'',1,'',0,NULL);
INSERT INTO `pages` VALUES(747,745,2,1,5,'Lorem ipsum dolor sit amet','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce vulputate magna sit amet neque tincidunt convallis. Sed in sapien in tellus hendrerit sollicitudin. Phasellus accumsan libero id risus tincidunt molestie sit amet sit amet augue. Maecenas turpis nunc, commodo id dapibus vel, blandit luctus nulla. Proin nibh risus, scelerisque quis condimentum nec, lobortis in velit. Duis sit amet lacus purus, at adipiscing massa. Vestibulum malesuada est nec risus ultricies lobortis. Sed lobortis ultricies tortor, non egestas velit pulvinar sed. Cras luctus leo at orci mollis id ultrices libero fermentum. Ut ac tortor ac dolor faucibus molestie in eu ligula. Phasellus pharetra varius elit sit amet pretium. Aliquam sapien quam, semper sed faucibus eget, imperdiet sed nulla. Nulla felis orci, feugiat vel posuere nec, porta eu turpis. Curabitur scelerisque vulputate turpis ut ornare. In fermentum feugiat volutpat.','2012-10-15 15:11:22','2013-02-02 12:26:46','127.0.0.1','127.0.0.1','lorem-ipsum-dolor-sit-amet','news_page.tpl',NULL,NULL,NULL,'',2,'2012-10-15',0,NULL,5,0,'aypfvgjxxscy',0,0,390,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(748,745,2,1,6,'Nunc eu urna orci','Suspendisse consectetur odio nec metus aliquet at posuere nibh tempus. Sed quis libero eget nibh fringilla accumsan ut at diam. In non metus sed tortor adipiscing adipiscing eget eu tellus. Nunc lacinia nulla non eros feugiat ac mattis ligula luctus. Nullam erat risus, faucibus eu eleifend ac, tincidunt quis elit. Maecenas tempor tortor sed magna tempor pharetra. Vestibulum in massa massa. Proin eget eros vitae sapien semper semper. Maecenas condimentum tempus eleifend. Phasellus velit turpis, sodales sed egestas eu, rhoncus vel nibh. Sed gravida luctus blandit. Suspendisse pretium libero in ipsum posuere ut molestie eros lacinia. Nulla facilisi. Cras tempor scelerisque ullamcorper. Nunc eu urna orci.','2012-10-15 15:11:31','2013-02-02 12:26:46','127.0.0.1','127.0.0.1','nunc-eu-urna-orci','news_page.tpl',NULL,NULL,NULL,'',3,'2012-10-15',0,NULL,5,0,'vdwdvzfnfckf',0,0,390,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(749,745,2,1,7,'Proin sed metus non lacus','Maecenas volutpat iaculis iaculis. Aliquam erat volutpat. Aenean rhoncus luctus cursus. Vestibulum accumsan commodo sodales. Nulla blandit cursus turpis, at vulputate nisi tempor at. Curabitur velit nulla, egestas ut molestie sed, placerat ac arcu. Proin sed metus non lacus sollicitudin faucibus sit amet et velit. Aenean et lacus at erat faucibus tristique. Fusce tincidunt, massa semper laoreet pharetra, tortor nisi cursus ipsum, a mattis arcu mauris eget purus. Fusce arcu neque, ullamcorper nec dignissim quis, porttitor non augue. Nam a varius eros. Donec libero arcu, accumsan a sagittis sed, facilisis quis leo. Quisque blandit facilisis urna, sed placerat augue vehicula vulputate. Nam ac dolor mauris, vitae hendrerit sem. Ut leo erat, imperdiet in faucibus volutpat, consectetur ut neque.','2012-10-15 15:11:43','2013-02-02 12:26:46','127.0.0.1','127.0.0.1','proin-sed-metus-non-lacus','news_page.tpl',NULL,NULL,NULL,'',5,'2012-10-15',0,NULL,5,0,'dvrjkpbwxfqt',0,0,390,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(750,659,13,1,19,'News','{{W name=newsNormal newsGroup=750 showAuthor=0}}','2013-02-02 12:25:48','2013-02-02 22:21:42','127.0.0.1','127.0.0.1','news','simple_page.tpl','','','','',3,NULL,0,'simple_page.tpl',60,0,'gtqmqzacavxt',0,0,659,'',0,'',0,NULL);
INSERT INTO `pages` VALUES(751,659,12,1,20,'Gallery','{{W name=galleryFancybox images=$imagesDB->getByBucket(737)}}','2013-02-02 12:25:55','2013-02-02 22:08:06','127.0.0.1','127.0.0.1','gallery','simple_page.tpl','','','','',5,NULL,0,'simple_page.tpl',60,0,'tzpspbaxkjqh',0,0,659,'',0,'',0,NULL);
INSERT INTO `pages` VALUES(752,659,11,1,21,'Group',' ','2013-02-02 12:26:00','2013-02-02 12:26:46','127.0.0.1','127.0.0.1','group','simple_page.tpl',NULL,NULL,NULL,NULL,2,NULL,0,NULL,60,0,'npttyayfgpxg',0,0,659,NULL,0,NULL,0,NULL);
INSERT INTO `pages` VALUES(753,659,3,1,22,'CMS Link','http://en.windu.org','2013-02-02 12:26:31','2013-02-04 09:00:24','127.0.0.1','127.0.0.1','cms-link','simple_page.tpl',NULL,NULL,NULL,'',3,NULL,0,NULL,60,0,'kffyhnnhbyns',0,0,659,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(754,750,2,1,999999,'Vestibulum molestie','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum suscipit vulputate rutrum. Maecenas dictum ultrices diam, a semper eros hendrerit a. Vivamus mattis varius odio tempus egestas. Quisque ornare vestibulum urna quis bibendum. Ut pharetra mi at justo semper non commodo orci blandit. Mauris sodales congue risus non lacinia. Cras tortor lectus, hendrerit vel faucibus sed, eleifend eget arcu. Praesent rutrum arcu aliquet mauris cursus gravida. Nulla varius commodo libero id interdum. Nullam tempus metus sagittis lacus adipiscing lobortis. Aenean quis nisl ipsum. Ut iaculis dolor vitae risus tincidunt bibendum. Suspendisse commodo cursus justo, ac tempus sem laoreet a. Proin in augue dolor, non lobortis lacus. Vestibulum molestie facilisis velit, a tempus neque sagittis eget.<br />
','2013-02-02 22:19:53','2013-02-02 22:19:53','127.0.0.1','127.0.0.1','vestibulum-molestie','simple_page.tpl',NULL,NULL,NULL,'',1,'2013-02-02',0,NULL,60,0,'akzdkpvzaqmb',0,0,659,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(755,750,2,1,999999,'Ut malesuada lacinia','Donec vestibulum aliquam urna, eu auctor lectus blandit sit amet. Praesent eget est in augue porta iaculis. Aliquam rutrum, justo vitae gravida dictum, ante ligula scelerisque magna, sed sollicitudin urna mauris eget est. Nam ac porttitor dolor. Sed laoreet molestie orci sed lacinia. Morbi tellus nibh, dapibus eget mattis et, varius nec orci. Vestibulum est elit, aliquam et aliquam ut, eleifend quis nunc. Proin vitae ligula nec lorem volutpat cursus. Praesent placerat nunc vitae nunc pharetra posuere. Nam eleifend porttitor purus.<br />
<br />
In sed augue ligula. Ut malesuada lacinia condimentum. Donec in nisi mauris, quis pretium diam. Etiam nec arcu id elit imperdiet gravida. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras bibendum consectetur tellus, a ultrices diam cursus in. Sed venenatis lacus vel metus vulputate euismod condimentum nulla consectetur. Duis bibendum commodo enim nec tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat facilisis vestibulum. Phasellus tincidunt euismod luctus. In quis diam arcu. Mauris metus odio, venenatis et sollicitudin hendrerit, molestie ac arcu. Fusce semper pulvinar nisl nec ullamcorper.','2013-02-02 22:20:03','2013-02-02 22:20:03','127.0.0.1','127.0.0.1','ut-malesuada-lacinia','simple_page.tpl',NULL,NULL,NULL,'',0,'2013-02-02',0,NULL,60,0,'zqvzwaabcnmg',0,0,659,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(756,750,2,1,999999,'Praesent posuere','Vivamus ornare interdum pharetra. Etiam at leo eget neque ullamcorper accumsan congue ut risus. Integer rhoncus iaculis mi consequat rutrum. Fusce bibendum tempor feugiat. Vivamus vitae eros dolor. Praesent vestibulum urna sit amet diam varius commodo at et elit. Sed gravida, quam eget dictum ultricies, odio justo sollicitudin tortor, vitae dignissim lectus nunc non sapien. Duis pellentesque aliquet nibh vel posuere.<br />
<br />
Praesent posuere scelerisque nisi, et bibendum libero facilisis ac. Etiam a enim id urna pharetra hendrerit. Vivamus vel nunc ac ligula scelerisque bibendum eget et nibh. Suspendisse fringilla cursus massa, id vestibulum nunc tempor sit amet. Aliquam auctor sem tempus nunc dignissim imperdiet. Nam sapien purus, aliquam ut pellentesque eu, feugiat id sapien. Aenean faucibus luctus pharetra. Quisque eu eros neque.','2013-02-02 22:20:15','2013-02-02 22:20:15','127.0.0.1','127.0.0.1','praesent-posuere','simple_page.tpl',NULL,NULL,NULL,'',0,'2013-02-02',0,NULL,60,0,'nktbvpvfwryn',0,0,659,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(757,750,2,1,999999,'Vivamus ornare','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum suscipit vulputate rutrum. Maecenas dictum ultrices diam, a semper eros hendrerit a. Vivamus mattis varius odio tempus egestas. Quisque ornare vestibulum urna quis bibendum. Ut pharetra mi at justo semper non commodo orci blandit. Mauris sodales congue risus non lacinia. Cras tortor lectus, hendrerit vel faucibus sed, eleifend eget arcu. Praesent rutrum arcu aliquet mauris cursus gravida. Nulla varius commodo libero id interdum. Nullam tempus metus sagittis lacus adipiscing lobortis. Aenean quis nisl ipsum. Ut iaculis dolor vitae risus tincidunt bibendum. Suspendisse commodo cursus justo, ac tempus sem laoreet a. Proin in augue dolor, non lobortis lacus. Vestibulum molestie facilisis velit, a tempus neque sagittis eget.<br />
<br />
Vivamus ornare interdum pharetra. Etiam at leo eget neque ullamcorper accumsan congue ut risus. Integer rhoncus iaculis mi consequat rutrum. Fusce bibendum tempor feugiat. Vivamus vitae eros dolor. Praesent vestibulum urna sit amet diam varius commodo at et elit. Sed gravida, quam eget dictum ultricies, odio justo sollicitudin tortor, vitae dignissim lectus nunc non sapien. Duis pellentesque aliquet nibh vel posuere.','2013-02-02 22:20:24','2013-02-02 22:20:24','127.0.0.1','127.0.0.1','vivamus-ornare','simple_page.tpl',NULL,NULL,NULL,'',0,'2013-02-02',0,NULL,60,0,'vkcjgzjnbjfw',0,0,659,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(758,750,2,1,999999,'Duis bibendum commodo','Donec vestibulum aliquam urna, eu auctor lectus blandit sit amet. Praesent eget est in augue porta iaculis. Aliquam rutrum, justo vitae gravida dictum, ante ligula scelerisque magna, sed sollicitudin urna mauris eget est. Nam ac porttitor dolor. Sed laoreet molestie orci sed lacinia. Morbi tellus nibh, dapibus eget mattis et, varius nec orci. Vestibulum est elit, aliquam et aliquam ut, eleifend quis nunc. Proin vitae ligula nec lorem volutpat cursus. Praesent placerat nunc vitae nunc pharetra posuere. Nam eleifend porttitor purus.<br />
<br />
In sed augue ligula. Ut malesuada lacinia condimentum. Donec in nisi mauris, quis pretium diam. Etiam nec arcu id elit imperdiet gravida. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras bibendum consectetur tellus, a ultrices diam cursus in. Sed venenatis lacus vel metus vulputate euismod condimentum nulla consectetur. Duis bibendum commodo enim nec tincidunt. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer placerat facilisis vestibulum. Phasellus tincidunt euismod luctus. In quis diam arcu. Mauris metus odio, venenatis et sollicitudin hendrerit, molestie ac arcu. Fusce semper pulvinar nisl nec ullamcorper.','2013-02-02 22:20:35','2013-02-02 22:20:35','127.0.0.1','127.0.0.1','duis-bibendum-commodo','simple_page.tpl',NULL,NULL,NULL,'',3,'2013-02-02',0,NULL,60,0,'zxrxjvcngvss',0,0,659,NULL,1,NULL,0,NULL);
INSERT INTO `pages` VALUES(759,474,12,1,999999,'Loga stopka','{{W name=galleryFancybox images=$imagesDB->getByBucket(759)}}','2013-02-04 10:57:42','2013-02-04 10:57:42','127.0.0.1','127.0.0.1','loga-stopka','simple_page.tpl',NULL,NULL,NULL,NULL,0,NULL,0,NULL,60,0,'swrqmzxyyvwf',0,0,390,NULL,0,NULL,0,NULL);


INSERT INTO `config` VALUES(1,99,1,'revision','1580','config.long.description.revision','config.short.description.revision','numeric');
INSERT INTO `config` VALUES(2,99,1,'install','0','config.long.description.install','config.short.description.install','bool');
INSERT INTO `config` VALUES(28,3,1,'template','standard2','config.long.description.template','config.short.description.template','string');
INSERT INTO `config` VALUES(29,0,1,'language-front','390','config.long.description.frontLanguage','config.short.description.frontLanguage','numeric');
INSERT INTO `config` VALUES(30,1,1,'imgGalleryWidth','186','config.long.description.imgGalleryWidth','config.short.description.imgGalleryWidth','numeric');
INSERT INTO `config` VALUES(31,1,1,'imgGalleryHeight','145','config.long.description.imgGalleryHeight','config.short.description.imgGalleryHeight','numeric');
INSERT INTO `config` VALUES(32,1,1,'imgGalleryFit','smart','config.long.description.imgGalleryFit','config.short.description.imgGalleryFit','string');
INSERT INTO `config` VALUES(33,1,1,'imgQuality','99','config.long.description.imgQuality','config.short.description.imgQuality','numeric');
INSERT INTO `config` VALUES(34,0,1,'systemDir','/','config.long.description.systemDir','config.short.description.systemDir','string');
INSERT INTO `config` VALUES(36,1,1,'newsCount','6','config.long.description.newsCount','config.short.description.newsCount','numeric');
INSERT INTO `config` VALUES(37,1,1,'newsLength','150','config.long.description.newsLength','config.short.description.newsLength','numeric');
INSERT INTO `config` VALUES(40,1,1,'newsSpan','4','config.long.description.newsSpan','config.short.description.newsSpan','numeric');
INSERT INTO `config` VALUES(41,0,1,'pageName','Windu','config.long.description.pageName','config.short.description.pageName','string');
INSERT INTO `config` VALUES(42,1,1,'newsBtnCssClass','btn','config.long.description.newsBtnCssClass','config.short.description.newsBtnCssClass','string');
INSERT INTO `config` VALUES(43,5,1,'cache','0','config.long.description.cache','config.short.description.cache','bool');
INSERT INTO `config` VALUES(44,5,1,'inPlaceEditor','1','config.long.description.inPlaceEditor','config.short.description.inPlaceEditor','bool');
INSERT INTO `config` VALUES(45,1,1,'commentsStatus','1','config.long.description.commentsStatus','config.short.description.commentsStatus','bool');
INSERT INTO `config` VALUES(46,1,1,'newsLengthTitle','100','config.long.description.newsLengthTitle','config.short.description.newsLengthTitle','numeric');
INSERT INTO `config` VALUES(47,1,1,'tagsCount','20','config.long.description.tagsCount','config.short.description.tagsCount','numeric');
INSERT INTO `config` VALUES(50,1,1,'sliderImageFit','smart','config.long.description.sliderImageFit','config.short.description.sliderImageFit','string');
INSERT INTO `config` VALUES(51,1,1,'sliderImageFilter','original','config.long.description.sliderImageFilter','config.short.description.sliderImageFilter','string');
INSERT INTO `config` VALUES(52,1,1,'sliderContentLength','300','config.long.description.sliderContentLenght','config.short.description.sliderContentLenght','numeric');
INSERT INTO `config` VALUES(53,1,1,'sliderCount','5','config.long.description.sliderCount','config.short.description.sliderCount','numeric');
INSERT INTO `config` VALUES(54,1,1,'imgSmallWidth','150','config.long.description.imgSmallWidth','config.short.description.imgSmallWidth','numeric');
INSERT INTO `config` VALUES(55,1,1,'imgSmallHeight','100','config.long.description.imgSmallHeight','config.short.description.imgSmallHeight','numeric');
INSERT INTO `config` VALUES(56,1,1,'imgMediumWidth','250','config.long.description.imgMediumWidth','config.short.description.imgMediumWidth','numeric');
INSERT INTO `config` VALUES(57,1,1,'imgMediumHeight','200','config.long.description.imgMediumHeight','config.short.description.imgMediumHeight','numeric');
INSERT INTO `config` VALUES(58,1,1,'imgBigWidth','500','config.long.description.imgBigWidth','config.short.description.imgBigWidth','numeric');
INSERT INTO `config` VALUES(59,1,1,'imgBigHeight','400','config.long.description.imgBigHeight','config.short.description.imgBigHeight','numeric');
INSERT INTO `config` VALUES(60,1,1,'imgFit','smart','config.long.description.imgFit','config.short.description.imgFit','string');
INSERT INTO `config` VALUES(61,1,1,'imgFilter','original','config.long.description.imgFilter','config.short.description.imgFilter','string');
INSERT INTO `config` VALUES(62,2,1,'userActive','0','config.long.description.userActive','config.short.description.userActive','bool');
INSERT INTO `config` VALUES(63,4,1,'mailingSendLimit','100','config.long.description.mailingSendLimit','config.short.description.mailingSendLimit','numeric');
INSERT INTO `config` VALUES(64,2,1,'userMailActivation','1','config.long.description.userMailActivation','config.short.description.userMailActivation','bool');
INSERT INTO `config` VALUES(65,1,1,'commentsLoggedUser','1','config.long.description.commentsLoggedUser','config.short.description.commentsLoggedUser','bool');
INSERT INTO `config` VALUES(66,5,1,'cacheLife','7200','config.long.description.cacheLife','config.short.description.cacheLife','numeric');
INSERT INTO `config` VALUES(67,5,1,'cacheResources','0','config.long.description.cacheResources','config.short.description.cacheResources','bool');
INSERT INTO `config` VALUES(74,99,1,'license','','config.long.description.license','config.short.description.license','string');
INSERT INTO `config` VALUES(99,99,1,'downloadedRevision','1076','config.long.description.downloadedRevision','config.short.description.downloadedRevision','numeric');
INSERT INTO `config` VALUES(100,99,1,'updateServerRevision','577','config.long.description.updateServerRevision','config.short.description.updateServerRevision','numeric');
INSERT INTO `config` VALUES(101,1,1,'imgGalleryFullWidth','1200','config.long.description.imgGalleryFullWidth','config.short.description.imgGalleryFullWidth','numeric');
INSERT INTO `config` VALUES(102,1,1,'imgGalleryFullHeight','1200','config.long.description.imgGalleryFullHeight','config.short.description.imgGalleryFullHeight','numeric');
INSERT INTO `config` VALUES(103,1,1,'contentListCount','20','config.long.description.contentListCount','config.short.description.contentListCount','numeric');
INSERT INTO `config` VALUES(104,99,1,'winduLink','1','config.long.description.winduLink','config.short.description.winduLink','bool');
INSERT INTO `config` VALUES(105,1,1,'editorCKEType','normal','config.long.description.editorCKEType','config.short.description.editorCKEType','string');
INSERT INTO `config` VALUES(109,0,1,'language-admin','390','config.long.description.adminLanguage','config.short.description.adminLanguage','numeric');
INSERT INTO `config` VALUES(110,5,1,'sitemap','0','config.long.description.sitemap','config.short.description.sitemap','bool');
INSERT INTO `config` VALUES(113,1,1,'contentListLength','200','config.long.description.contentListLength','config.short.description.contentListLength','numeric');
INSERT INTO `config` VALUES(116,4,1,'firewallRequestLimit','2000','config.long.description.firewallRequestLimit','config.short.description.firewallRequestLimit','numeric');
INSERT INTO `config` VALUES(184,4,1,'firewallEmail','','config.long.description.firewallEmail','config.short.description.firewallEmail','string');
INSERT INTO `config` VALUES(185,4,1,'SystemRun-monitoringAlexa','0','config.long.description.SystemRun-monitoringAlexa','config.short.description.SystemRun-monitoringAlexa','bool');
INSERT INTO `config` VALUES(186,4,1,'SystemRun-monitoringGoogle','0','config.long.description.SystemRun-monitoringGoogle','config.short.description.SystemRun-monitoringGoogle','bool');
INSERT INTO `config` VALUES(187,5,1,'timezone','Europe/Amsterdam','config.long.description.timezone','config.short.description.timezone','string');
INSERT INTO `config` VALUES(188,4,1,'SystemRun-firewall','0','config.long.description.SystemRun-firewall','config.short.description.SystemRun-firewall','bool');
INSERT INTO `config` VALUES(189,4,1,'SystemRun-log','1','config.long.description.SystemRun-log','config.short.description.SystemRun-log','bool');
INSERT INTO `config` VALUES(190,4,1,'SystemRun-requestLog','1','config.long.description.SystemRun-requestLog','config.short.description.SystemRun-requestLog','bool');
INSERT INTO `config` VALUES(191,4,1,'SystemRun-monitoring','1','config.long.description.SystemRun-monitoring','config.short.description.SystemRun-monitoring','bool');
INSERT INTO `config` VALUES(192,5,1,'SystemRun-statistic','1','config.long.description.SystemRun-statistic','config.short.description.SystemRun-statistic','bool');
INSERT INTO `config` VALUES(193,4,1,'firewallRequestLimit','2000','config.long.description.firewallRequestLimit','config.short.description.firewallRequestLimit','numeric');
INSERT INTO `config` VALUES(194,4,1,'firewallEmail','','config.long.description.firewallEmail','config.short.description.firewallEmail','string');
INSERT INTO `config` VALUES(195,4,1,'SystemRun-monitoringAlexa','0','config.long.description.SystemRun-monitoringAlexa','config.short.description.SystemRun-monitoringAlexa','bool');
INSERT INTO `config` VALUES(196,4,1,'SystemRun-monitoringGoogle','0','config.long.description.SystemRun-monitoringGoogle','config.short.description.SystemRun-monitoringGoogle','bool');
INSERT INTO `config` VALUES(197,5,1,'timezone','0','config.long.description.timezone','config.short.description.timezone','string');
INSERT INTO `config` VALUES(198,4,1,'SystemRun-firewall','0','config.long.description.SystemRun-firewall','config.short.description.SystemRun-firewall','bool');
INSERT INTO `config` VALUES(199,4,1,'SystemRun-log','1','config.long.description.SystemRun-log','config.short.description.SystemRun-log','bool');
INSERT INTO `config` VALUES(200,4,1,'SystemRun-requestLog','1','config.long.description.SystemRun-requestLog','config.short.description.SystemRun-requestLog','bool');
INSERT INTO `config` VALUES(201,4,1,'SystemRun-monitoring','1','config.long.description.SystemRun-monitoring','config.short.description.SystemRun-monitoring','bool');
INSERT INTO `config` VALUES(202,5,1,'SystemRun-statistic','1','config.long.description.SystemRun-statistic','config.short.description.SystemRun-statistic','bool');
INSERT INTO `config` VALUES ('204','99','0','userMode-1','1',null,null,null);

INSERT INTO `config` VALUES ('205','5','0','hour_move_acceslogs','1',null,null,null);

INSERT INTO `config` VALUES ('206','5','0','hour_rss_update','1',null,null,null);

INSERT INTO `config` VALUES ('207','5','0','day_write_system_status','1',null,null,null);

INSERT INTO `config` VALUES ('208','5','0','day_clean_firewall','1',null,null,null);

INSERT INTO `config` VALUES ('209','5','0','day_sitemap','1',null,null,null);

INSERT INTO `config` VALUES ('210','5','0','week_compact_versions','1',null,null,null);

INSERT INTO `config` VALUES ('211','5','0','week_flush_cache','1',null,null,null);

INSERT INTO `config` VALUES ('212','5','0','week_delete_old_requestlogs','1',null,null,null);

INSERT INTO `config` VALUES ('213','5','0','week_delete_old_logs','1',null,null,null);

INSERT INTO `config` VALUES ('214','5','0','month_vacum','1',null,null,null);

INSERT INTO `config` VALUES ('215','5','0','month_clean_firewall','1',null,null,null);
INSERT INTO `config` VALUES ('216','5','0','month_delete_thumbs','0',null,null,null);

INSERT INTO `config` VALUES ('217','5','0','month_clean_backups','0',null,null,null);

INSERT INTO `config` VALUES ('218','5','0','month_backup','0',null,null,null);

INSERT INTO `images` VALUES(1,'icon-390',999999,'image/q','hmazzz.png','pl',NULL,374,'2012-10-13 14:15:48','2012-10-13 14:15:48','127.0.0.1','127.0.0.1','hdbsqxfbzyjf','png',16,11,NULL);
INSERT INTO `images` VALUES(2,'icon-659',999999,'image/c','bcffth.png','gb',NULL,599,'2012-10-13 14:16:05','2012-10-13 14:16:05','127.0.0.1','127.0.0.1','brdqxhfdwbwx','png',16,11,NULL);
INSERT INTO `images` VALUES(4,737,1,'image/h','vzraxh.jpeg','Phasellus viverra felis vel posuere','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec bibendum semper nunc, sit amet condimentum mauris consectetur vitae. Phasellus viverra, felis vel posuere fermentum, ipsum libero gravida turpis, ut tincidunt mauris mi eu risus. Curabitur lacinia commodo libero id congue. Quisque tincidunt ipsum et turpis iaculis eleifend. Phasellus laoreet mattis dignissim. In sapien lacus, rutrum eu viverra et, rhoncus at nisi. Morbi commodo, arcu sed facilisis feugiat, massa metus consectetur ante, et pulvinar tellus odio aliquet tellus. Suspendisse lacinia leo vitae augue ornare vitae fermentum nibh dignissim. Suspendisse ac lorem nunc. Ut sed arcu justo.',235770,'2013-02-02 21:46:28','2013-02-03 09:38:28','127.0.0.1','127.0.0.1','qgahmhfnkrmm','jpeg',1600,742,NULL);
INSERT INTO `images` VALUES(5,737,2,'image/f','nqcprd.jpeg','Class aptent taciti sociosqu','Etiam quis quam odio, eu convallis turpis. Sed porttitor ligula quis risus fringilla vulputate eget eget leo. Sed facilisis, lectus non condimentum faucibus, risus enim lobortis eros, vitae suscipit mi nulla a enim. Donec adipiscing mi fringilla nisi tincidunt a porta est ultricies. Donec lacinia, sapien ut pellentesque volutpat, massa nibh ultrices diam, at vehicula ante risus ut nisl. Mauris ac elementum nisl. Donec fermentum porta nisl, eget ultrices sem vulputate at. Aenean vehicula fermentum leo, quis feugiat nunc rutrum eu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam euismod placerat ultricies. Nulla pharetra massa sapien. Morbi sodales erat nec leo aliquet sit amet vestibulum tellus hendrerit.',322806,'2013-02-02 21:46:28','2013-02-03 09:39:24','127.0.0.1','127.0.0.1','ftqsspqzgpjn','jpeg',1600,774,NULL);
INSERT INTO `images` VALUES(6,737,3,'image/n','rxxqbx.jpeg','Duis volutpat mollis','Vestibulum dictum, lorem vel faucibus bibendum, eros velit porta mi, in vulputate purus est vel dui. Praesent sagittis consequat magna, vitae tincidunt ligula consectetur et. Donec pellentesque risus felis, sodales sollicitudin sapien. Morbi consectetur vehicula convallis. In hac habitasse platea dictumst. Nullam vel erat a libero pulvinar ornare. Morbi eu enim id felis bibendum venenatis eget quis eros. Duis volutpat mollis quam, non pellentesque nibh blandit nec. Sed eget tortor turpis.',184190,'2013-02-02 21:46:28','2013-02-03 09:39:40','127.0.0.1','127.0.0.1','njtdzgwmywvq','jpeg',1600,804,NULL);
INSERT INTO `images` VALUES(7,737,4,'image/w','mknmbn.jpeg','Donec consectetur accumsan nunc','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam at risus risus, quis feugiat arcu. Suspendisse sed elit dolor, in pulvinar orci. Ut in dolor enim. Etiam sagittis felis at nisl accumsan vel gravida libero ultricies. Donec consectetur accumsan nunc, id viverra orci euismod id. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed orci purus, viverra ac adipiscing vitae, lacinia et nibh. Donec sollicitudin suscipit ligula, ut sagittis lacus posuere et. Donec condimentum accumsan bibendum. Pellentesque aliquam viverra pharetra. Nulla dapibus pretium justo. Phasellus varius ipsum a tortor convallis lobortis. Praesent pellentesque iaculis metus vel facilisis. Donec luctus accumsan consectetur. Phasellus vestibulum porttitor auctor. Quisque odio arcu, pharetra at aliquam vitae, malesuada non libero.',242691,'2013-02-02 21:46:28','2013-02-03 09:40:19','127.0.0.1','127.0.0.1','bpqrgnwspdqg','jpeg',1600,624,NULL);
INSERT INTO `images` VALUES(8,'user-60',999999,'image/r','fpaxya.jpeg','Krakow_6_by_Andulka',NULL,322806,'2013-02-04 09:24:01','2013-02-04 09:24:01','127.0.0.1','127.0.0.1','pfwcddwnavrb','jpeg',1600,774,NULL);
INSERT INTO `images` VALUES(9,759,1,'image/h','amnqzf.png','jcd','http://www.jcd.pl',16223,'2013-02-04 10:57:53','2013-02-04 11:04:17','127.0.0.1','127.0.0.1','dkxtgktgndnr','png',200,100,NULL);
INSERT INTO `images` VALUES(10,759,5,'image/z','mwspst.png','webstation','http://www.webstation.com.pl',7001,'2013-02-04 10:57:53','2013-02-04 11:05:04','127.0.0.1','127.0.0.1','mgsxgnztbnvc','png',200,100,NULL);
INSERT INTO `images` VALUES(11,759,3,'image/z','czvzyr.png','position','http://www.position.com.pl',7096,'2013-02-04 10:57:53','2013-02-04 11:04:45','127.0.0.1','127.0.0.1','qadgntnhgyrm','png',200,100,NULL);
INSERT INTO `images` VALUES(12,759,2,'image/h','gkcafg.png','webprojector','http://www.webprojector.org',7779,'2013-02-04 10:57:53','2013-02-04 11:04:33','127.0.0.1','127.0.0.1','ywbhchmatjpa','png',200,100,NULL);
INSERT INTO `images` VALUES(13,759,4,'image/t','swqnag.png','wysoko','http://www.wysoko.org',7336,'2013-02-04 10:57:53','2013-02-04 11:04:53','127.0.0.1','127.0.0.1','hqxqpdzrykhd','png',200,100,NULL);


INSERT INTO `usertypes` VALUES(9,0,'Administrator',0,'admin*');
INSERT INTO `usertypes` VALUES(14,9,'Page User',1,'front*');
INSERT INTO `usertypes` VALUES(17,0,'Admin Main',0,'adminIndex*,adminDoController');
INSERT INTO `usertypes` VALUES(18,17,'Content',0,'adminContent*');
INSERT INTO `usertypes` VALUES(19,17,'Editor',0,'adminContent*,adminBackup*,adminSystem*');
